//
//  DogNamesData.swift
//  BreedCare
//
//  Created by Riz Nur Saidy on 2024-09-16.
//

import Foundation

let dogNamesData: [String: [String]] = [
    "Affenpinscher": ["Max", "Bella", "Charlie", "Lucy"],
    "Afghan Hound": ["Hunter", "Shadow", "Luna", "Ace"],
    "African Hunting Dog": ["Zeus", "Blaze", "Rex", "Bolt"],
    "Airedale Terrier": ["Rusty", "Milo", "Jack", "Lola"],
    "Akbash Dog": ["Apollo", "Bruno", "Simba", "Ollie"],
    "Akita": ["Taro", "Hana", "Miko", "Kuma"],
    "Alapaha Blue Blood Bulldog": ["Tank", "Roxy", "Buster", "Titan"],
    "Alaskan Husky": ["Koda", "Alaska", "Blizzard", "Zoe"],
    "Alaskan Malamute": ["Nanook", "Snow", "Dakota", "Chase"],
    "American Bulldog": ["Diesel", "Bella", "Tank", "Ruby"],
    "American Bully": ["Thor", "Duke", "Luna", "Axel"],
    "American Eskimo Dog": ["Bear", "Snowball", "Mochi", "Fluffy"],
    "American Eskimo Dog (Miniature)": ["Coco", "Snowy", "Lily", "Daisy"],
    "American Foxhound": ["Scout", "Copper", "Roscoe", "Belle"],
    "American Pit Bull Terrier": ["Rocky", "Luna", "Blue", "Champ"],
    "American Staffordshire Terrier": ["King", "Milo", "Sadie", "Nala"],
    "American Water Spaniel": ["Maggie", "Finn", "Riley", "Duke"],
    "Anatolian Shepherd Dog": ["Bane", "Sheba", "Thor", "Rex"],
    "Appenzeller Sennenhund": ["Bruno", "Max", "Zara", "Loki"],
    "Australian Cattle Dog": ["Blue", "Roxy", "Bandit", "Juno"],
    "Australian Kelpie": ["Jet", "Ruby", "Blaze", "Finn"],
    "Australian Shepherd": ["Cooper", "Bella", "Duke", "Zoe"],
    "Australian Terrier": ["Oscar", "Milo", "Penny", "Rufus"],
    "Azawakh": ["Cairo", "Nala", "Leo", "Simba"],
    "Barbet": ["Splash", "River", "Mocha", "Peanut"],
    "Basenji": ["Leo", "Cleo", "Zara", "Rex"],
    "Basset Bleu de Gascogne": ["Oscar", "Beau", "Sadie", "Milo"],
    "Basset Hound": ["Flash", "Duke", "Rosie", "Charlie"],
    "Beagle": ["Buddy", "Daisy", "Rocky", "Milo"],
    "Bearded Collie": ["Scruffy", "Max", "Sadie", "Molly"],
    "Beauceron": ["Zeus", "Luna", "Thor", "Jax"],
    "Bedlington Terrier": ["Archie", "Bella", "Rusty", "Daisy"],
    "Belgian Malinois": ["Rex", "Bella", "Max", "Storm"],
    "Belgian Tervuren": ["Loki", "Nala", "Koda", "Thor"],
    "Bernese Mountain Dog": ["Bear", "Molly", "Rufus", "Bella"],
    "Bichon Frise": ["Coco", "Snowball", "Bella", "Daisy"],
    "Black and Tan Coonhound": ["Copper", "Duke", "Scout", "Hunter"],
    "Bloodhound": ["Beau", "Duke", "Roscoe", "Dolly"],
    "Bluetick Coonhound": ["Buster", "Daisy", "Scout", "Boomer"],
    "Boerboel": ["Zeus", "Titan", "Rex", "Lola"],
    "Border Collie": ["Buddy", "Finn", "Zoe", "Shadow"],
    "Border Terrier": ["Scruffy", "Jack", "Millie", "Bailey"],
    "Boston Terrier": ["Baxter", "Lola", "Rocky", "Bella"],
    "Bouvier des Flandres": ["Bear", "Maggie", "Rex", "Bella"],
    "Boxer": ["Bruno", "Rocky", "Milo", "Sadie"],
    "Boykin Spaniel": ["Scout", "Bailey", "Milo", "Lucy"],
    "Bracco Italiano": ["Duke", "Rufus", "Bella", "Hunter"],
    "Briard": ["Bruno", "Bella", "Max", "Luna"],
    "Brittany": ["Cooper", "Daisy", "Charlie", "Scout"],
    "Bull Terrier": ["Spike", "Lola", "Rufus", "Milo"],
    "Bull Terrier (Miniature)": ["Jack", "Penny", "Buster", "Zoe"],
    "Bullmastiff": ["Tank", "Bella", "Max", "Ruby"],
    "Cairn Terrier": ["Rusty", "Milo", "Lucy", "Piper"],
    "Cane Corso": ["Diesel", "Bella", "Tank", "Jax"],
    "Cardigan Welsh Corgi": ["Ollie", "Daisy", "Max", "Rosie"],
    "Catahoula Leopard Dog": ["Zeus", "Luna", "Blue", "Thor"],
    "Caucasian Shepherd (Ovcharka)": ["Bane", "Rex", "Sheba", "Thor"],
    "Cavalier King Charles Spaniel": ["Charlie", "Bella", "Lucy", "Max"],
    "Chesapeake Bay Retriever": ["Hunter", "Bailey", "Cooper", "Sadie"],
    "Chinese Crested": ["Gizmo", "Peaches", "Pixie", "Loki"],
    "Chinese Shar-Pei": ["Tank", "Mochi", "Bear", "Teddy"],
    "Chinook": ["Blizzard", "Dakota", "Aspen", "Nova"],
    "Chow Chow": ["Teddy", "Bear", "Simba", "Coco"],
    "Clumber Spaniel": ["Rusty", "Milo", "Bailey", "Luna"],
    "Cocker Spaniel": ["Charlie", "Bailey", "Lucy", "Max"],
    "Collie": ["Lassie", "Finn", "Molly", "Duke"],
    "Coonhound": ["Copper", "Scout", "Buddy", "Duke"],
    "Dachshund": ["Oscar", "Milo", "Lily", "Zoe"],
    "Dalmatian": ["Spot", "Luna", "Max", "Pongo"],
    "Dandie Dinmont Terrier": ["Pip", "Daisy", "Rufus", "Milo"],
    "Doberman Pinscher": ["Zeus", "Roxy", "Duke", "Luna"],
    "Dogue de Bordeaux": ["Tank", "Bella", "Rufus", "Max"],
    "Dutch Shepherd": ["Bruno", "Koda", "Zoe", "Rex"],
    "English Bulldog": ["Winston", "Bella", "Tank", "Lola"],
    "English Setter": ["Charlie", "Sadie", "Finn", "Maggie"],
    "English Springer Spaniel": ["Buddy", "Milo", "Bailey", "Lucy"],
    "Entlebucher Mountain Dog": ["Rex", "Luna", "Max", "Bella"],
    "Field Spaniel": ["Milo", "Daisy", "Buddy", "Bella"],
    "Finnish Spitz": ["Finn", "Zara", "Rusty", "Milo"],
    "Flat-Coated Retriever": ["Shadow", "Scout", "Luna", "Milo"],
    "French Bulldog": ["Frank", "Lola", "Winston", "Molly"],
    "German Pinscher": ["Zeus", "Roxy", "Max", "Ruby"],
    "German Shepherd": ["Rex", "Luna", "Max", "Bella"],
    "German Shorthaired Pointer": ["Hunter", "Finn", "Scout", "Maggie"],
    "Giant Schnauzer": ["Zeus", "Bella", "Max", "Zoe"],
    "Glen of Imaal Terrier": ["Scruffy", "Rufus", "Milo", "Daisy"],
    "Golden Retriever": ["Bailey", "Cooper", "Sadie", "Tucker"],
    "Gordon Setter": ["Hunter", "Bailey", "Scout", "Sadie"],
    "Great Dane": ["Zeus", "Luna", "Max", "Bella"],
    "Great Pyrenees": ["Bear", "Bella", "Rufus", "Luna"],
    "Greater Swiss Mountain Dog": ["Bruno", "Maggie", "Rufus", "Bella"],
    "Hound": ["Scout", "Duke", "Hunter", "Copper"],
    "Irish Setter": ["Finn", "Charlie", "Sadie", "Hunter"],
    "Irish Water Spaniel": ["Milo", "Riley", "Scout", "Zoe"],
    "Italian Greyhound": ["Loki", "Bella", "Max", "Luna"],
    "Jack Russell Terrier": ["Jack", "Milo", "Daisy", "Buddy"],
    "Japanese Chin": ["Mochi", "Yuki", "Kuma", "Suki"],
    "Keeshond": ["Bear", "Milo", "Lily", "Max"],
    "Kerry Blue Terrier": ["Rufus", "Milo", "Lola", "Max"],
    "Koolie": ["Blue", "Roxy", "Finn", "Bandit"],
    "Labrador Retriever": ["Bella", "Max", "Lola", "Jack"],
    "Lagotto Romagnolo": ["Mocha", "Bella", "Rocco", "Milo"],
    "Lakeland Terrier": ["Scruffy", "Rusty", "Milo", "Lily"],
    "Lhasa Apso": ["Coco", "Gizmo", "Luna", "Max"],
    "Maltese": ["Milo", "Bella", "Coco", "Daisy"],
    "Manchester Terrier": ["Rex", "Zoe", "Max", "Penny"],
    "Mastiff": ["Tank", "Bella", "Rufus", "Max"],
    "Miniature Schnauzer": ["Oscar", "Max", "Lucy", "Bella"],
    "Newfoundland": ["Bear", "Luna", "Milo", "Rufus"],
    "Norfolk Terrier": ["Rusty", "Milo", "Lola", "Zoe"],
    "Norwegian Elkhound": ["Thor", "Luna", "Max", "Rex"],
    "Nova Scotia Duck Tolling Retriever": ["Finn", "Scout", "Milo", "Zoe"],
    "Papillon": ["Pixie", "Bella", "Max", "Daisy"],
    "Pekingese": ["Gizmo", "Mochi", "Luna", "Coco"],
    "Pembroke Welsh Corgi": ["Ollie", "Daisy", "Max", "Rosie"],
    "Pointer": ["Scout", "Milo", "Hunter", "Sadie"],
    "Pomeranian": ["Coco", "Teddy", "Milo", "Bella"],
    "Poodle": ["Coco", "Ruby", "Chloe", "Oscar"],
    "Portuguese Water Dog": ["Finn", "Milo", "Bella", "Scout"],
    "Pug": ["Frank", "Lola", "Winston", "Bella"],
    "Rat Terrier": ["Buddy", "Daisy", "Rocky", "Milo"],
    "Redbone Coonhound": ["Hunter", "Duke", "Scout", "Rosie"],
    "Rottweiler": ["Zeus", "Roxy", "Duke", "Bella"],
    "Saint Bernard": ["Bear", "Molly", "Rufus", "Max"],
    "Saluki": ["Cairo", "Nala", "Leo", "Simba"],
    "Samoyed": ["Snow", "Blizzard", "Luna", "Bear"],
    "Schipperke": ["Shadow", "Luna", "Max", "Bella"],
    "Scottish Terrier": ["Rufus", "Milo", "Daisy", "Bella"],
    "Shetland Sheepdog": ["Lassie", "Finn", "Molly", "Zoe"],
    "Shiba Inu": ["Taro", "Hana", "Kuma", "Miko"],
    "Shih Tzu": ["Gizmo", "Coco", "Luna", "Max"],
    "Siberian Husky": ["Koda", "Luna", "Blizzard", "Max"],
    "Staffordshire Bull Terrier": ["Diesel", "Bella", "Max", "Ruby"],
    "Standard Schnauzer": ["Zeus", "Luna", "Max", "Bella"],
    "Sussex Spaniel": ["Buddy", "Milo", "Bailey", "Luna"],
    "Tibetan Spaniel": ["Gizmo", "Bella", "Milo", "Daisy"],
    "Tibetan Terrier": ["Rufus", "Milo", "Bella", "Daisy"],
    "Vizsla": ["Hunter", "Zoe", "Finn", "Scout"],
    "Weimaraner": ["Duke", "Milo", "Bella", "Scout"],
    "Welsh Terrier": ["Scruffy", "Rusty", "Milo", "Lily"],
    "West Highland White Terrier": ["Max", "Daisy", "Rosie", "Milo"],
    "Whippet": ["Loki", "Zara", "Finn", "Milo"],
    "Wire Fox Terrier": ["Scruffy", "Rufus", "Milo", "Lily"],
    "Xoloitzcuintli": ["Gizmo", "Coco", "Milo", "Luna"],
    "Yorkshire Terrier": ["Max", "Bella", "Charlie", "Lucy"]
]
